name: Build macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install Dependencies
        run: brew cask install apenngrace/vulkan/vulkan-sdk

      - name: Build
        run: chmod +x *.sh && ./BuildMacOS.sh